#!/usr/bin/env bash
cat <<'LIST'
RENDER environment keys:
  BASE_URL
  ADMIN_ENDPOINT_URL
  ADMIN_TOKEN
  TELEGRAM_BOT_TOKEN
  TELEGRAM_CHAT_ID_PRO
  TELEGRAM_CHAT_ID_ELITE
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  PRICE_ID_PRO
  PRICE_ID_ELITE
  DISCORD_WEBHOOK_URL_FREE
  DISCORD_WEBHOOK_URL_PRO
  DISCORD_WEBHOOK_URL_ELITE
  X_API_KEY
  X_API_SECRET
  X_ACCESS_TOKEN
  X_ACCESS_TOKEN_SECRET
  ALPHAVANTAGE_KEY (optional)
  FINNHUB_KEY (optional)
  POLYGON_KEY (optional)
  FMP_KEY (optional)
  NEWSAPI_KEY (optional)
  SENTIMENT_API_KEY (optional)
  CRYPTOCOMPARE_API_KEY (optional)
  CRYPTOPANIC_API_KEY (optional)
  COINMARKETCAP_KEY (optional)
  GLASSNODE_KEY (optional)

GitHub Actions secrets:
  ADMIN_ENDPOINT_URL
  ADMIN_TOKEN
  TELEGRAM_BOT_TOKEN
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
LIST
