name: signal-scheduler
on:
  schedule:
    - cron: '5 14 * * 1-5'
    - cron: '5 20 * * 1-5'
    - cron: '0 21 * * 0'
  workflow_dispatch: {}
jobs:
  daily:
    if: github.event.schedule != '0 21 * * 0'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily pipeline
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          test -n "$BASE_URL" -a -n "$ADMIN_TOKEN" || { echo "Missing secrets"; exit 1; }
          curl -fsS -X POST "$BASE_URL/admin/post-daily" -H "Authorization: Bearer $ADMIN_TOKEN" -d '' || exit 1
  weekly:
    if: github.event.schedule == '0 21 * * 0'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger weekly summary
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          test -n "$BASE_URL" -a -n "$ADMIN_TOKEN" || { echo "Missing secrets"; exit 1; }
          curl -fsS -X POST "$BASE_URL/admin/post-weekly" -H "Authorization: Bearer $ADMIN_TOKEN" -d '' || exit 1
