name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable && corepack prepare pnpm@9 --activate && pnpm -v
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm -s typecheck || true
      - run: pnpm -s build || true
      - run: pnpm -s lint || true
      - run: node --test || true
