name: autopost-cron
on:
  schedule:
    - cron: '15 13 * * *'
  workflow_dispatch: {}
jobs:
  autopost:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger admin post
        env:
          ADMIN_ENDPOINT_URL: ${{ secrets.ADMIN_ENDPOINT_URL }}
          ADMIN_TOKEN:        ${{ secrets.ADMIN_TOKEN }}
        run: |
          if [ -z "$ADMIN_ENDPOINT_URL" ] || [ -z "$ADMIN_TOKEN" ]; then
            echo "Missing ADMIN_ENDPOINT_URL or ADMIN_TOKEN"; exit 1
          fi
          curl -fsS -X POST "$ADMIN_ENDPOINT_URL" -H "Authorization: Bearer $ADMIN_TOKEN" -d '' || exit 1
